const days = [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
];

const statNames = {
    'null' : 'null',
    'lifemax' : 'Life',
    'manamax' : 'Mana',
    'staminamax' : 'Stamina',
    'str': 'Strength',
    'dex': 'Dexterity',
    'int': 'Intelligence',
    'will': 'Will',
    'luck': 'Luck',
    'defence' : 'Defense',
    'magicdefense' : 'Magic Defense',
    'shockcancellation_def' : 'While Dampen Shock is Active, Defense',
    'shockcancellation_magicdefence' : 'While Dampen Shock is Active, Magic Defense',
    'prot' : 'Protection',
    'attmin': 'Min Damage',
    'attmax': 'Max Damage',
    'crit': 'Critical',
    'critical' : 'Critical',
    'rate': 'Balance',
    'balance' : 'Balance',
    'wattmax' : 'Max Injury',
    'wattmin' : 'Min Injury',
    'magicattack' : 'Magic Attack',
    'musicbuff_bonus' : 'Music Buff Effect',
    'musicbuff_duration' : 'Music Buff Duration',
    'alchemy_water' : 'Water Alchemy Damage',
    'alchemy_fire' : 'Fire Alchemy Damage',
    'alchemy_wire' : 'Wind Alchemy Damage',
    'alchemist_product_success_rate' : 'Alchemy Success Rate',
    'synthesis' : 'Synthesis Success Rate',
    'dissolution' : 'Fragmentation Success Rate',
    'crystal_making' : 'Mana Crystallization Success Rate',
    'barrier_life' : 'Barrier Spikes Life',
    'frozen_blast_duraion' : 'Frozen Blast Duration',
    'frozen_blast_degree' : 'Frozen Blast Angle',
    'marionette_life' : 'Marionette Life',
    'marionette_defense' : 'Marionette Defense',
    'marionette_protect' :'Marionette Protection',
    'marionette_magic_defense' : 'Marionette Magic Defense',
    'marionette_damage_max' : 'Marionette Max Damage',
    'marionette_damage_min' : 'Marionette Min Damage',
    'marionette_control_critical' : 'Marionette Critical',
    'commerce_credibility' : 'Commerce Reward',
    'commerce_discount' : 'Commerce Discount',
    'staminause_revised' : 'Stamina Usage',
    'mana_saving' : 'Mana Usage Reduction',
    'bombexpert' : 'Explosion Defense',
    'stompdefence' : 'Stomp Defense',
    'poison_immune' : 'Poison Immunity',
    'fast_attack' : 'Attack Speed Increase',
    'combatpower' : 'Combat Power',
    'product_quality_bonus' : 'Production Quality',
    'lance_piercing' : 'Piercing Level',
    'timewarp_count' : 'Time Shift Cooldown Ignore Count',
};

const conditions = {
    0: 'Poison',
    1: 'Deadly',
    2: 'Potion Poison',
    183: 'Respite Aftereffect',
};

const ranks = {
    1: 'F',
    2: 'E',
    3: 'D',
    4: 'C',
    5: 'B',
    6: 'A',
    7: '9',
    8: '8',
    9: '7',
    10: '6',
    11: '5',
    12: '4',
    13: '3',
    14: '2',
    15: '1',
    16: 'Dan 1',
    17: 'Dan 2',
    18: 'Dan 3',
};

module.exports = {
    days,
    statNames,
    conditions,
    ranks,
}
